name: CI

on:
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # Force the use of BuildKit for Docker
  DOCKER_BUILDKIT: 1

jobs:
  # run linter on the code
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'common/ unit_test/'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 12

  # build project
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.2.0
        with:
          tool-cache: true
          large-packages: false

      - name: Checkout built branch
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docker
        run: docker build -t gcc_env docker/gcc

      - name: Configure
        run: |
          docker run -v ${{ github.workspace }}:/work gcc_env \
            cmake -B build \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DMini_MDFT_ENABLE_TESTS=ON
            
      - name: Build
        run: |
          docker run -v ${{ github.workspace }}:/work gcc_env \
            cmake --build build -j 4

      - name: Test
        run: |
          docker run -v ${{github.workspace}}:/work gcc_env \
            ctest --test-dir build/batched/unit_test -C ${{env.BUILD_TYPE}} --output-on-failure
