# SPDX-FileCopyrightText: (C) The Mini-MDFT development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

# Clean old Docker images that are too old periodically or manually.

name: Cleanup base images

on:
  schedule:
    - cron: "0 3 2,16 * *" # every 2nd and 16th of the month at 3am UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup old images
        uses: SmartsquareGmbH/delete-old-packages@v0.8.1
        with:
          user: yasahi-hpc
          type: container
          names: |
            Mini-MDFT/base_nvcc_main
            Mini-MDFT/base_nvcc_pr
            Mini-MDFT/base_rocm_main
            Mini-MDFT/base_rocm_pr
            Mini-MDFT/base_gcc_main
            Mini-MDFT/base_gcc_pr
            Mini-MDFT/base_clang_main
            Mini-MDFT/base_clang_pr
            Mini-MDFT/base_intel_main
            Mini-MDFT/base_intel_pr
